import sys, time
from struct import *
from PyQt5.QtCore import QRunnable, Qt, QThreadPool
from PyQt5.QtWidgets import * 
from PyQt5.QtGui import * 
from PyQt5 import QtCore, QtGui, QtWidgets
from IPython import embed
from time import sleep

from numpy import True_

class Runnable(QRunnable):
    def __init__(self):
        super().__init__()
        #Display refresh rate
        self.refreshRate = 60
        self.loopRate = 0
        
        # RPM Guage Vars
        self.RPMDec = 0
        self.greenRPM = "color:rgb(75,200,77)"
        self.redRPM = "color:rgb(255,100,50)"
        self.blankRPM = "color:rgb(0,0,0)"
        self.RPMArr = []*27
        self.RPMDots = {1 : ui.r0.setStyleSheet, 2 :  ui.r0_2.setStyleSheet,3 :  ui.r0_3.setStyleSheet,4 :  ui.r0_4.setStyleSheet,5 :  ui.r0_5.setStyleSheet,6 :  ui.r0_6.setStyleSheet,7 :  ui.r0_7.setStyleSheet,8 :  ui.r0_8.setStyleSheet,9 :  ui.r0_9.setStyleSheet,10 :  ui.r0_10.setStyleSheet,11 :  ui.r0_11.setStyleSheet,12 :  ui.r0_12.setStyleSheet,13 :  ui.r0_13.setStyleSheet,14 :  ui.r0_14.setStyleSheet,15 :  ui.r0_15.setStyleSheet,16 :  ui.r0_16.setStyleSheet,17 :  ui.r0_17.setStyleSheet,18 :  ui.r0_18.setStyleSheet,19 :  ui.r0_19.setStyleSheet,20 :  ui.r0_20.setStyleSheet,21 :  ui.r0_21.setStyleSheet,22 :  ui.r0_22.setStyleSheet,23 :  ui.r0_23.setStyleSheet,24 :  ui.r0_24.setStyleSheet,25 :  ui.r0_25.setStyleSheet,26 :  ui.r0_26.setStyleSheet}
        self.RPMColourHist = [0]*27
        
        for i in range(len(self.RPMDots)): #set everything to 0
            self.RPMDots[i+1](self.blankRPM)
        
        self.upDown = True #This is for dummy data
        
        #RPM
        self.RPMOld = 0        
        

    def run(self):
        while True:
            #refresh Zone
            # sleep(0.01)
            self.loopRate += 1
            # if self.currentFrame % 60 == 0
            self.RPMGuageDisplay()
            
            if self.upDown == True:
                self.RPMDec += 1
            if self.upDown == False:
                self.RPMDec -= 1
                
            if self.RPMDec > 10000 and self.upDown == True:
                self.upDown = False
            if self.RPMDec < 0 and self.upDown == False:
                self.upDown = True
            print(self.RPMColourHist, self.RPMDec, self.upDown)
            
            
            if self.RPMOld != self.RPMDec: #Rev counter in numbers
                ui.RPMDec.setText(str(self.RPMDec))

    
    def RPMGuageDisplay(self): #26 lines
        self.RPMScaled = round((self.RPMDec) * (26 / 8500))
        # print("scaled", self.RPMScaled)
        for i in range(len(self.RPMDots)):
            # print(i)
            if i + 1 < self.RPMScaled and i + 1 < 26 and self.RPMColourHist[i + 1] == 0:
                self.RPMDots[i + 1](self.greenRPM)
                self.RPMColourHist[i + 1] = 1
            if i + 1 > self.RPMScaled and self.RPMColourHist[i + 1] == 1:
                self.RPMDots[i + 1](self.blankRPM)
                self.RPMColourHist[i + 1] = 0
            if i + 1 < self.RPMScaled and i + 1 >= 26 and self.RPMColourHist[i + 1] == 0:
                self.RPMDots[i + 1](self.redRPM)
                self.RPMColourHist[i + 1] = 1

            
            
        

            
            
            
            
        
#
            


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.setMinimumSize(QtCore.QSize(723, 475))
        MainWindow.setMaximumSize(QtCore.QSize(723, 723))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.SizeVerCursor))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setToolTipDuration(7)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 723, 475))
        self.graphicsView.setStyleSheet("background-image: url(C:/Users/Will/OneDrive - Middlesex University/Inventions/IsaacRX8/carbonTexture.png); background-repeat: no-repeat; background-position: center;\\)\n"
"")
        self.graphicsView.setObjectName("graphicsView")
        self.speedDec = QtWidgets.QLabel(self.centralwidget)
        self.speedDec.setGeometry(QtCore.QRect(350, 271, 161, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(70)
        font.setBold(True)
        font.setWeight(75)
        self.speedDec.setFont(font)
        self.speedDec.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.speedDec.setAutoFillBackground(False)
        self.speedDec.setStyleSheet("color:rgb(255,100,115)")
        self.speedDec.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.speedDec.setMidLineWidth(-1)
        self.speedDec.setAlignment(QtCore.Qt.AlignCenter)
        self.speedDec.setObjectName("speedDec")
        self.gearDec = QtWidgets.QLabel(self.centralwidget)
        self.gearDec.setGeometry(QtCore.QRect(171, 243, 181, 191))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(140)
        font.setBold(True)
        font.setWeight(75)
        self.gearDec.setFont(font)
        self.gearDec.setStyleSheet("color:rgb(75,200,77)\n"
"")
        self.gearDec.setAlignment(QtCore.Qt.AlignCenter)
        self.gearDec.setObjectName("gearDec")
        self.fuelDec = QtWidgets.QLabel(self.centralwidget)
        self.fuelDec.setGeometry(QtCore.QRect(549, 363, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.fuelDec.setFont(font)
        self.fuelDec.setStyleSheet("color:rgb(75,200,77)")
        self.fuelDec.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fuelDec.setObjectName("fuelDec")
        self.r0 = QtWidgets.QFrame(self.centralwidget)
        self.r0.setGeometry(QtCore.QRect(170, 121, 11, 38))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r0.sizePolicy().hasHeightForWidth())
        self.r0.setSizePolicy(sizePolicy)
        self.r0.setStyleSheet("color:rgb(75,200,77)")
        self.r0.setFrameShadow(QtWidgets.QFrame.Plain)
        self.r0.setLineWidth(57)
        self.r0.setFrameShape(QtWidgets.QFrame.HLine)
        self.r0.setObjectName("r0")
        self.RPMDec = QtWidgets.QLabel(self.centralwidget)
        self.RPMDec.setGeometry(QtCore.QRect(250, 139, 231, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(70)
        font.setBold(True)
        font.setWeight(75)
        self.RPMDec.setFont(font)
        self.RPMDec.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.RPMDec.setAutoFillBackground(False)
        self.RPMDec.setStyleSheet("color:rgb(170,215,75)")
        self.RPMDec.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.RPMDec.setMidLineWidth(-1)
        self.RPMDec.setAlignment(QtCore.Qt.AlignCenter)
        self.RPMDec.setObjectName("RPMDec")
        self.r0_2 = QtWidgets.QFrame(self.centralwidget)
        self.r0_2.setGeometry(QtCore.QRect(185, 112, 11, 38))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r0_2.sizePolicy().hasHeightForWidth())
        self.r0_2.setSizePolicy(sizePolicy)
        self.r0_2.setStyleSheet("color:rgb(75,200,77)")
        self.r0_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.r0_2.setLineWidth(57)
        self.r0_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.r0_2.setObjectName("r0_2")
        self.r0_3 = QtWidgets.QFrame(self.centralwidget)
        self.r0_3.setGeometry(QtCore.QRect(200, 103, 11, 38))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r0_3.sizePolicy().hasHeightForWidth())
        self.r0_3.setSizePolicy(sizePolicy)
        self.r0_3.setStyleSheet("color:rgb(75,200,77)")
        self.r0_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.r0_3.setLineWidth(57)
        self.r0_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.r0_3.setObjectName("r0_3")
        self.r0_4 = QtWidgets.QFrame(self.centralwidget)
        self.r0_4.setGeometry(QtCore.QRect(215, 94, 11, 38))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r0_4.sizePolicy().hasHeightForWidth())
        self.r0_4.setSizePolicy(sizePolicy)
        self.r0_4.setStyleSheet("color:rgb(75,200,77)")
        self.r0_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.r0_4.setLineWidth(57)
        self.r0_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.r0_4.setObjectName("r0_4")
        self.r0_5 = QtWidgets.QFrame(self.centralwidget)
        self.r0_5.setGeometry(QtCore.QRect(230, 88, 11, 38))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r0_5.sizePolicy().hasHeightForWidth())
        self.r0_5.setSizePolicy(sizePolicy)
        self.r0_5.setStyleSheet("color:rgb(75,200,77)")
        self.r0_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.r0_5.setLineWidth(57)
        self.r0_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.r0_5.setObjectName("r0_5")
        self.r0_6 = QtWidgets.QFrame(self.centralwidget)
        self.r0_6.setGeometry(QtCore.QRect(245, 80, 11, 38))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r0_6.sizePolicy().hasHeightForWidth())
        self.r0_6.setSizePolicy(sizePolicy)
        self.r0_6.setStyleSheet("color:rgb(75,200,77)")
        self.r0_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.r0_6.setLineWidth(57)
        self.r0_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.r0_6.setObjectName("r0_6")
        self.r0_7 = QtWidgets.QFrame(self.centralwidget)
        self.r0_7.setGeometry(QtCore.QRect(260, 76, 11, 38))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r0_7.sizePolicy().hasHeightForWidth())
        self.r0_7.setSizePolicy(sizePolicy)
        self.r0_7.setStyleSheet("color:rgb(75,200,77)")
        self.r0_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.r0_7.setLineWidth(57)
        self.r0_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.r0_7.setObjectName("r0_7")
        self.r0_8 = QtWidgets.QFrame(self.centralwidget)
        self.r0_8.setGeometry(QtCore.QRect(275, 72, 11, 38))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r0_8.sizePolicy().hasHeightForWidth())
        self.r0_8.setSizePolicy(sizePolicy)
        self.r0_8.setStyleSheet("color:rgb(75,200,77)")
        self.r0_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.r0_8.setLineWidth(57)
        self.r0_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.r0_8.setObjectName("r0_8")
        self.r0_9 = QtWidgets.QFrame(self.centralwidget)
        self.r0_9.setGeometry(QtCore.QRect(290, 69, 11, 38))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r0_9.sizePolicy().hasHeightForWidth())
        self.r0_9.setSizePolicy(sizePolicy)
        self.r0_9.setStyleSheet("color:rgb(75,200,77)")
        self.r0_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.r0_9.setLineWidth(57)
        self.r0_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.r0_9.setObjectName("r0_9")
        self.r0_10 = QtWidgets.QFrame(self.centralwidget)
        self.r0_10.setGeometry(QtCore.QRect(305, 67, 11, 38))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r0_10.sizePolicy().hasHeightForWidth())
        self.r0_10.setSizePolicy(sizePolicy)
        self.r0_10.setStyleSheet("color:rgb(75,200,77)")
        self.r0_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.r0_10.setLineWidth(57)
        self.r0_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.r0_10.setObjectName("r0_10")
        self.r0_11 = QtWidgets.QFrame(self.centralwidget)
        self.r0_11.setGeometry(QtCore.QRect(320, 67, 11, 38))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r0_11.sizePolicy().hasHeightForWidth())
        self.r0_11.setSizePolicy(sizePolicy)
        self.r0_11.setStyleSheet("color:rgb(75,200,77)")
        self.r0_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.r0_11.setLineWidth(57)
        self.r0_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.r0_11.setObjectName("r0_11")
        self.r0_12 = QtWidgets.QFrame(self.centralwidget)
        self.r0_12.setGeometry(QtCore.QRect(335, 67, 11, 38))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r0_12.sizePolicy().hasHeightForWidth())
        self.r0_12.setSizePolicy(sizePolicy)
        self.r0_12.setStyleSheet("color:rgb(75,200,77)")
        self.r0_12.setFrameShadow(QtWidgets.QFrame.Plain)
        self.r0_12.setLineWidth(57)
        self.r0_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.r0_12.setObjectName("r0_12")
        self.r0_13 = QtWidgets.QFrame(self.centralwidget)
        self.r0_13.setGeometry(QtCore.QRect(350, 67, 11, 38))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r0_13.sizePolicy().hasHeightForWidth())
        self.r0_13.setSizePolicy(sizePolicy)
        self.r0_13.setStyleSheet("color:rgb(75,200,77)")
        self.r0_13.setFrameShadow(QtWidgets.QFrame.Plain)
        self.r0_13.setLineWidth(57)
        self.r0_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.r0_13.setObjectName("r0_13")
        self.r0_14 = QtWidgets.QFrame(self.centralwidget)
        self.r0_14.setGeometry(QtCore.QRect(365, 67, 11, 38))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r0_14.sizePolicy().hasHeightForWidth())
        self.r0_14.setSizePolicy(sizePolicy)
        self.r0_14.setStyleSheet("color:rgb(75,200,77)")
        self.r0_14.setFrameShadow(QtWidgets.QFrame.Plain)
        self.r0_14.setLineWidth(57)
        self.r0_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.r0_14.setObjectName("r0_14")
        self.r0_15 = QtWidgets.QFrame(self.centralwidget)
        self.r0_15.setGeometry(QtCore.QRect(380, 67, 11, 38))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r0_15.sizePolicy().hasHeightForWidth())
        self.r0_15.setSizePolicy(sizePolicy)
        self.r0_15.setStyleSheet("color:rgb(75,200,77)")
        self.r0_15.setFrameShadow(QtWidgets.QFrame.Plain)
        self.r0_15.setLineWidth(57)
        self.r0_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.r0_15.setObjectName("r0_15")
        self.r0_16 = QtWidgets.QFrame(self.centralwidget)
        self.r0_16.setGeometry(QtCore.QRect(395, 67, 11, 38))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r0_16.sizePolicy().hasHeightForWidth())
        self.r0_16.setSizePolicy(sizePolicy)
        self.r0_16.setStyleSheet("color:rgb(75,200,77)")
        self.r0_16.setFrameShadow(QtWidgets.QFrame.Plain)
        self.r0_16.setLineWidth(57)
        self.r0_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.r0_16.setObjectName("r0_16")
        self.r0_17 = QtWidgets.QFrame(self.centralwidget)
        self.r0_17.setGeometry(QtCore.QRect(395, 67, 11, 38))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r0_17.sizePolicy().hasHeightForWidth())
        self.r0_17.setSizePolicy(sizePolicy)
        self.r0_17.setStyleSheet("color:rgb(75,200,77)")
        self.r0_17.setFrameShadow(QtWidgets.QFrame.Plain)
        self.r0_17.setLineWidth(57)
        self.r0_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.r0_17.setObjectName("r0_17")
        self.r0_18 = QtWidgets.QFrame(self.centralwidget)
        self.r0_18.setGeometry(QtCore.QRect(410, 67, 11, 38))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r0_18.sizePolicy().hasHeightForWidth())
        self.r0_18.setSizePolicy(sizePolicy)
        self.r0_18.setStyleSheet("color:rgb(75,200,77)")
        self.r0_18.setFrameShadow(QtWidgets.QFrame.Plain)
        self.r0_18.setLineWidth(57)
        self.r0_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.r0_18.setObjectName("r0_18")
        self.r0_19 = QtWidgets.QFrame(self.centralwidget)
        self.r0_19.setGeometry(QtCore.QRect(425, 67, 11, 38))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r0_19.sizePolicy().hasHeightForWidth())
        self.r0_19.setSizePolicy(sizePolicy)
        self.r0_19.setStyleSheet("color:rgb(75,200,77)")
        self.r0_19.setFrameShadow(QtWidgets.QFrame.Plain)
        self.r0_19.setLineWidth(57)
        self.r0_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.r0_19.setObjectName("r0_19")
        self.r0_20 = QtWidgets.QFrame(self.centralwidget)
        self.r0_20.setGeometry(QtCore.QRect(440, 67, 11, 38))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r0_20.sizePolicy().hasHeightForWidth())
        self.r0_20.setSizePolicy(sizePolicy)
        self.r0_20.setStyleSheet("color:rgb(75,200,77)")
        self.r0_20.setFrameShadow(QtWidgets.QFrame.Plain)
        self.r0_20.setLineWidth(57)
        self.r0_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.r0_20.setObjectName("r0_20")
        self.r0_21 = QtWidgets.QFrame(self.centralwidget)
        self.r0_21.setGeometry(QtCore.QRect(455, 67, 11, 38))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r0_21.sizePolicy().hasHeightForWidth())
        self.r0_21.setSizePolicy(sizePolicy)
        self.r0_21.setStyleSheet("color:rgb(75,200,77)")
        self.r0_21.setFrameShadow(QtWidgets.QFrame.Plain)
        self.r0_21.setLineWidth(57)
        self.r0_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.r0_21.setObjectName("r0_21")
        self.r0_22 = QtWidgets.QFrame(self.centralwidget)
        self.r0_22.setGeometry(QtCore.QRect(470, 67, 11, 38))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r0_22.sizePolicy().hasHeightForWidth())
        self.r0_22.setSizePolicy(sizePolicy)
        self.r0_22.setStyleSheet("color:rgb(75,200,77)")
        self.r0_22.setFrameShadow(QtWidgets.QFrame.Plain)
        self.r0_22.setLineWidth(57)
        self.r0_22.setFrameShape(QtWidgets.QFrame.HLine)
        self.r0_22.setObjectName("r0_22")
        self.r0_23 = QtWidgets.QFrame(self.centralwidget)
        self.r0_23.setGeometry(QtCore.QRect(485, 67, 11, 38))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r0_23.sizePolicy().hasHeightForWidth())
        self.r0_23.setSizePolicy(sizePolicy)
        self.r0_23.setStyleSheet("color:rgb(75,200,77)")
        self.r0_23.setFrameShadow(QtWidgets.QFrame.Plain)
        self.r0_23.setLineWidth(57)
        self.r0_23.setFrameShape(QtWidgets.QFrame.HLine)
        self.r0_23.setObjectName("r0_23")
        self.r0_24 = QtWidgets.QFrame(self.centralwidget)
        self.r0_24.setGeometry(QtCore.QRect(500, 67, 11, 38))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r0_24.sizePolicy().hasHeightForWidth())
        self.r0_24.setSizePolicy(sizePolicy)
        self.r0_24.setStyleSheet("color:rgb(75,200,77)")
        self.r0_24.setFrameShadow(QtWidgets.QFrame.Plain)
        self.r0_24.setLineWidth(57)
        self.r0_24.setFrameShape(QtWidgets.QFrame.HLine)
        self.r0_24.setObjectName("r0_24")
        self.r0_25 = QtWidgets.QFrame(self.centralwidget)
        self.r0_25.setGeometry(QtCore.QRect(515, 67, 11, 38))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r0_25.sizePolicy().hasHeightForWidth())
        self.r0_25.setSizePolicy(sizePolicy)
        self.r0_25.setStyleSheet("color:rgb(75,200,77)")
        self.r0_25.setFrameShadow(QtWidgets.QFrame.Plain)
        self.r0_25.setLineWidth(57)
        self.r0_25.setFrameShape(QtWidgets.QFrame.HLine)
        self.r0_25.setObjectName("r0_25")
        self.r0_26 = QtWidgets.QFrame(self.centralwidget)
        self.r0_26.setGeometry(QtCore.QRect(530, 67, 11, 38))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r0_26.sizePolicy().hasHeightForWidth())
        self.r0_26.setSizePolicy(sizePolicy)
        self.r0_26.setAutoFillBackground(False)
        self.r0_26.setStyleSheet("color:rgb(255,100,50)")
        self.r0_26.setFrameShadow(QtWidgets.QFrame.Plain)
        self.r0_26.setLineWidth(57)
        self.r0_26.setFrameShape(QtWidgets.QFrame.HLine)
        self.r0_26.setObjectName("r0_26")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(28, 121, 108, 3))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(28, 223, 108, 3))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(28, 325, 108, 3))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(576, 121, 108, 3))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(576, 223, 108, 3))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(576, 325, 108, 3))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(200, 223, 308, 3))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.AFRDec = QtWidgets.QLabel(self.centralwidget)
        self.AFRDec.setGeometry(QtCore.QRect(20, 155, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.AFRDec.setFont(font)
        self.AFRDec.setStyleSheet("color:rgb(75,200,77)")
        self.AFRDec.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.AFRDec.setObjectName("AFRDec")
        self.battVoltDec = QtWidgets.QLabel(self.centralwidget)
        self.battVoltDec.setGeometry(QtCore.QRect(20, 259, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.battVoltDec.setFont(font)
        self.battVoltDec.setStyleSheet("color:rgb(190,190,220)")
        self.battVoltDec.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.battVoltDec.setObjectName("battVoltDec")
        self.AFRLabel = QtWidgets.QLabel(self.centralwidget)
        self.AFRLabel.setGeometry(QtCore.QRect(28, 130, 151, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.AFRLabel.setFont(font)
        self.AFRLabel.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.AFRLabel.setAutoFillBackground(False)
        self.AFRLabel.setStyleSheet("color:rgb(150,215,75)")
        self.AFRLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.AFRLabel.setMidLineWidth(-1)
        self.AFRLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.AFRLabel.setObjectName("AFRLabel")
        self.batteryLabel = QtWidgets.QLabel(self.centralwidget)
        self.batteryLabel.setGeometry(QtCore.QRect(28, 230, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.batteryLabel.setFont(font)
        self.batteryLabel.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.batteryLabel.setAutoFillBackground(False)
        self.batteryLabel.setStyleSheet("color:rgb(150,215,75)")
        self.batteryLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.batteryLabel.setMidLineWidth(-1)
        self.batteryLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.batteryLabel.setObjectName("batteryLabel")
        self.coolantTLabel = QtWidgets.QLabel(self.centralwidget)
        self.coolantTLabel.setGeometry(QtCore.QRect(576, 30, 151, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.coolantTLabel.setFont(font)
        self.coolantTLabel.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.coolantTLabel.setAutoFillBackground(False)
        self.coolantTLabel.setStyleSheet("color:rgb(150,215,75)")
        self.coolantTLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.coolantTLabel.setMidLineWidth(-1)
        self.coolantTLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.coolantTLabel.setObjectName("coolantTLabel")
        self.engineTLabel = QtWidgets.QLabel(self.centralwidget)
        self.engineTLabel.setGeometry(QtCore.QRect(576, 130, 151, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.engineTLabel.setFont(font)
        self.engineTLabel.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.engineTLabel.setAutoFillBackground(False)
        self.engineTLabel.setStyleSheet("color:rgb(150,215,75)")
        self.engineTLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.engineTLabel.setMidLineWidth(-1)
        self.engineTLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.engineTLabel.setObjectName("engineTLabel")
        self.coolantTDec = QtWidgets.QLabel(self.centralwidget)
        self.coolantTDec.setGeometry(QtCore.QRect(549, 55, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.coolantTDec.setFont(font)
        self.coolantTDec.setStyleSheet("color:rgb(190,190,220)")
        self.coolantTDec.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coolantTDec.setObjectName("coolantTDec")
        self.engineTDec = QtWidgets.QLabel(self.centralwidget)
        self.engineTDec.setGeometry(QtCore.QRect(549, 156, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.engineTDec.setFont(font)
        self.engineTDec.setStyleSheet("color:rgb(75,200,77)")
        self.engineTDec.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.engineTDec.setObjectName("engineTDec")
        self.RPMLabel = QtWidgets.QLabel(self.centralwidget)
        self.RPMLabel.setGeometry(QtCore.QRect(167, 80, 22, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.RPMLabel.setFont(font)
        self.RPMLabel.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.RPMLabel.setAutoFillBackground(False)
        self.RPMLabel.setStyleSheet("color:rgb(170,215,75)")
        self.RPMLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.RPMLabel.setMidLineWidth(-1)
        self.RPMLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.RPMLabel.setObjectName("RPMLabel")
        self.RPMLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.RPMLabel_2.setGeometry(QtCore.QRect(219, 49, 22, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.RPMLabel_2.setFont(font)
        self.RPMLabel_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.RPMLabel_2.setAutoFillBackground(False)
        self.RPMLabel_2.setStyleSheet("color:rgb(170,215,75)")
        self.RPMLabel_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.RPMLabel_2.setMidLineWidth(-1)
        self.RPMLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.RPMLabel_2.setObjectName("RPMLabel_2")
        self.RPMLabel_3 = QtWidgets.QLabel(self.centralwidget)
        self.RPMLabel_3.setGeometry(QtCore.QRect(280, 30, 22, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.RPMLabel_3.setFont(font)
        self.RPMLabel_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.RPMLabel_3.setAutoFillBackground(False)
        self.RPMLabel_3.setStyleSheet("color:rgb(170,215,75)")
        self.RPMLabel_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.RPMLabel_3.setMidLineWidth(-1)
        self.RPMLabel_3.setAlignment(QtCore.Qt.AlignCenter)
        self.RPMLabel_3.setObjectName("RPMLabel_3")
        self.RPMLabel_4 = QtWidgets.QLabel(self.centralwidget)
        self.RPMLabel_4.setGeometry(QtCore.QRect(340, 30, 22, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.RPMLabel_4.setFont(font)
        self.RPMLabel_4.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.RPMLabel_4.setAutoFillBackground(False)
        self.RPMLabel_4.setStyleSheet("color:rgb(170,215,75)")
        self.RPMLabel_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.RPMLabel_4.setMidLineWidth(-1)
        self.RPMLabel_4.setAlignment(QtCore.Qt.AlignCenter)
        self.RPMLabel_4.setObjectName("RPMLabel_4")
        self.RPMLabel_5 = QtWidgets.QLabel(self.centralwidget)
        self.RPMLabel_5.setGeometry(QtCore.QRect(400, 30, 22, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.RPMLabel_5.setFont(font)
        self.RPMLabel_5.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.RPMLabel_5.setAutoFillBackground(False)
        self.RPMLabel_5.setStyleSheet("color:rgb(170,215,75)")
        self.RPMLabel_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.RPMLabel_5.setMidLineWidth(-1)
        self.RPMLabel_5.setAlignment(QtCore.Qt.AlignCenter)
        self.RPMLabel_5.setObjectName("RPMLabel_5")
        self.RPMLabel_6 = QtWidgets.QLabel(self.centralwidget)
        self.RPMLabel_6.setGeometry(QtCore.QRect(460, 30, 22, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.RPMLabel_6.setFont(font)
        self.RPMLabel_6.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.RPMLabel_6.setAutoFillBackground(False)
        self.RPMLabel_6.setStyleSheet("color:rgb(170,215,75)")
        self.RPMLabel_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.RPMLabel_6.setMidLineWidth(-1)
        self.RPMLabel_6.setAlignment(QtCore.Qt.AlignCenter)
        self.RPMLabel_6.setObjectName("RPMLabel_6")
        self.RPMLabel_7 = QtWidgets.QLabel(self.centralwidget)
        self.RPMLabel_7.setGeometry(QtCore.QRect(520, 30, 22, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.RPMLabel_7.setFont(font)
        self.RPMLabel_7.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.RPMLabel_7.setAutoFillBackground(False)
        self.RPMLabel_7.setStyleSheet("color:rgb(255,100,50)")
        self.RPMLabel_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.RPMLabel_7.setMidLineWidth(-1)
        self.RPMLabel_7.setAlignment(QtCore.Qt.AlignCenter)
        self.RPMLabel_7.setObjectName("RPMLabel_7")
        self.fuelLabel = QtWidgets.QLabel(self.centralwidget)
        self.fuelLabel.setGeometry(QtCore.QRect(576, 336, 151, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.fuelLabel.setFont(font)
        self.fuelLabel.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.fuelLabel.setAutoFillBackground(False)
        self.fuelLabel.setStyleSheet("color:rgb(150,215,75)")
        self.fuelLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fuelLabel.setMidLineWidth(-1)
        self.fuelLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.fuelLabel.setObjectName("fuelLabel")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(170, 105, 3, 10))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(230, 72, 3, 10))
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(290, 53, 3, 10))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setGeometry(QtCore.QRect(350, 53, 3, 10))
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(self.centralwidget)
        self.line_12.setGeometry(QtCore.QRect(410, 53, 3, 10))
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_13 = QtWidgets.QFrame(self.centralwidget)
        self.line_13.setGeometry(QtCore.QRect(470, 53, 3, 10))
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.line_14 = QtWidgets.QFrame(self.centralwidget)
        self.line_14.setGeometry(QtCore.QRect(530, 53, 3, 10))
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.pedalLabel = QtWidgets.QFrame(self.centralwidget)
        self.pedalLabel.setGeometry(QtCore.QRect(170, 426, 371, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pedalLabel.sizePolicy().hasHeightForWidth())
        self.pedalLabel.setSizePolicy(sizePolicy)
        self.pedalLabel.setStyleSheet("color:rgb(52,52,52)")
        self.pedalLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.pedalLabel.setLineWidth(57)
        self.pedalLabel.setFrameShape(QtWidgets.QFrame.HLine)
        self.pedalLabel.setObjectName("pedalLabel")
        self.PedalLabel = QtWidgets.QLabel(self.centralwidget)
        self.PedalLabel.setGeometry(QtCore.QRect(300, 426, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.PedalLabel.setFont(font)
        self.PedalLabel.setStyleSheet("color:rgb(75,200,77)")
        self.PedalLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.PedalLabel.setObjectName("PedalLabel")
        self.pedalLabel_2 = QtWidgets.QFrame(self.centralwidget)
        self.pedalLabel_2.setGeometry(QtCore.QRect(170, 426, 371, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pedalLabel_2.sizePolicy().hasHeightForWidth())
        self.pedalLabel_2.setSizePolicy(sizePolicy)
        self.pedalLabel_2.setStyleSheet("color:rgb(75,200,77)")
        self.pedalLabel_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.pedalLabel_2.setLineWidth(57)
        self.pedalLabel_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.pedalLabel_2.setObjectName("pedalLabel_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.speedDec.setText(_translate("MainWindow", "176"))
        self.gearDec.setText(_translate("MainWindow", "N"))
        self.fuelDec.setText(_translate("MainWindow", "100"))
        self.RPMDec.setText(_translate("MainWindow", "0"))
        self.AFRDec.setText(_translate("MainWindow", "11.02"))
        self.battVoltDec.setText(_translate("MainWindow", "13.80"))
        self.AFRLabel.setText(_translate("MainWindow", "A.F.R."))
        self.batteryLabel.setText(_translate("MainWindow", "Battery (v)"))
        self.coolantTLabel.setText(_translate("MainWindow", "Coolant T."))
        self.engineTLabel.setText(_translate("MainWindow", "Engine T."))
        self.coolantTDec.setText(_translate("MainWindow", "90"))
        self.engineTDec.setText(_translate("MainWindow", "108"))
        self.RPMLabel.setText(_translate("MainWindow", "20"))
        self.RPMLabel_2.setText(_translate("MainWindow", "30"))
        self.RPMLabel_3.setText(_translate("MainWindow", "40"))
        self.RPMLabel_4.setText(_translate("MainWindow", "50"))
        self.RPMLabel_5.setText(_translate("MainWindow", "60"))
        self.RPMLabel_6.setText(_translate("MainWindow", "70"))
        self.RPMLabel_7.setText(_translate("MainWindow", "80"))
        self.fuelLabel.setText(_translate("MainWindow", "Fual Tank %"))
        self.PedalLabel.setText(_translate("MainWindow", "Pedal %"))

    def runTasks(self):
            threadCount = QThreadPool.globalInstance().maxThreadCount()
            pool = QThreadPool.globalInstance()
            runnable = Runnable()
            pool.start(runnable)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    ui.runTasks()
    MainWindow.show()
    sys.exit(app.exec_())
